/* The following code was generated by JFlex 1.4.3 on 5/2/14 3:06 AM */

package com.hoho.conkitty;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import static com.hoho.conkitty.psi.ConkittyTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 5/2/14 3:06 AM from the specification file
 * <tt>/Users/hoho/Work/conkittyPlugin/src/com/hoho/conkitty/Conkitty.flex</tt>
 */
abstract class _ConkittyLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int IN_TEMPLATE = 2;
  public static final int NO_JS = 10;
  public static final int YYINITIAL = 0;
  public static final int MULTILINE_JS = 12;
  public static final int IN_CALL = 6;
  public static final int AFTER_CALL = 4;
  public static final int IN_COMMENT = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  1,  1,  4,  4,  5, 5
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\0\1\6"+
    "\1\43\1\37\1\45\1\50\1\10\1\44\1\46\1\5\1\57\1\61"+
    "\1\11\1\42\1\4\12\14\1\12\2\0\1\56\2\0\1\47\1\15"+
    "\1\40\1\21\1\34\1\24\1\40\1\35\1\22\1\32\1\51\1\40"+
    "\1\25\1\30\1\36\1\23\1\27\1\40\1\20\1\16\1\17\2\40"+
    "\1\31\1\26\1\33\1\40\1\52\1\7\1\53\1\60\1\13\1\0"+
    "\32\41\1\54\1\0\1\55\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\1\3\1\4\3\2\1\5\4\2"+
    "\1\6\1\2\1\7\2\2\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\15\13\2\1\21"+
    "\1\2\3\22\4\23\1\24\3\1\2\25\1\0\1\26"+
    "\3\0\1\26\3\0\1\23\1\15\1\27\1\15\1\30"+
    "\5\0\1\31\16\0\1\32\1\0\1\22\1\32\1\23"+
    "\1\32\1\25\1\32\1\25\1\26\2\0\1\5\1\33"+
    "\2\0\1\34\3\0\1\34\1\22\12\0\1\22\1\23"+
    "\2\25\5\0\1\34\3\0\1\35\3\0\2\35\1\25"+
    "\15\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\u012c\0\u015e"+
    "\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258\0\u028a\0\u02bc\0\u02ee"+
    "\0\u0320\0\u012c\0\u0352\0\u012c\0\u0384\0\u03b6\0\u012c\0\u012c"+
    "\0\u012c\0\u012c\0\u012c\0\u012c\0\u012c\0\u012c\0\u03e8\0\u041a"+
    "\0\u044c\0\u041a\0\u047e\0\u04b0\0\u04e2\0\u0514\0\u0546\0\u0578"+
    "\0\u05aa\0\u05dc\0\u060e\0\u0640\0\u0672\0\u06a4\0\u06d6\0\u0708"+
    "\0\u073a\0\u076c\0\u079e\0\u07d0\0\u012c\0\u0802\0\u0834\0\u0866"+
    "\0\u0898\0\u08ca\0\u08fc\0\u092e\0\u0960\0\u0992\0\u09c4\0\u09f6"+
    "\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe\0\u02ee\0\u0320\0\u0af0\0\u0384"+
    "\0\u0b22\0\u0b54\0\u041a\0\u0b86\0\u0bb8\0\u041a\0\u0bea\0\u0c1c"+
    "\0\u0c4e\0\u0c80\0\u0cb2\0\u0ce4\0\u0d16\0\u0d48\0\u0d7a\0\u0dac"+
    "\0\u0dde\0\u0e10\0\u0e42\0\u0e74\0\u041a\0\u0ea6\0\u0ed8\0\u06a4"+
    "\0\u0f0a\0\u073a\0\u0f3c\0\u0802\0\u0f6e\0\u012c\0\u0fa0\0\u0fd2"+
    "\0\u0a8c\0\u012c\0\u1004\0\u1036\0\u1068\0\u109a\0\u10cc\0\u10fe"+
    "\0\u1130\0\u0bb8\0\u1162\0\u1194\0\u11c6\0\u11f8\0\u122a\0\u125c"+
    "\0\u128e\0\u12c0\0\u12f2\0\u1324\0\u1356\0\u1388\0\u13ba\0\u012c"+
    "\0\u13ec\0\u141e\0\u1450\0\u1482\0\u14b4\0\u012c\0\u14e6\0\u1518"+
    "\0\u154a\0\u041a\0\u157c\0\u15ae\0\u15e0\0\u06a4\0\u073a\0\u0802"+
    "\0\u1612\0\u1644\0\u1676\0\u16a8\0\u16da\0\u170c\0\u173e\0\u1770"+
    "\0\u17a2\0\u17d4\0\u1806\0\u1838\0\u186a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\7\2\10\1\11\1\12\1\7\1\13\1\7\1\14"+
    "\1\15\1\16\24\15\1\17\2\15\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\15\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\7\2\10\1\37"+
    "\1\12\1\7\1\13\1\7\1\14\1\40\1\41\2\42"+
    "\1\43\1\44\1\45\1\42\1\46\1\42\1\47\1\50"+
    "\2\42\1\51\1\52\1\53\5\42\1\17\1\42\1\54"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\55"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\7\2\10\1\37\1\12\1\7\1\13\1\7\1\14"+
    "\1\56\1\41\6\56\1\57\15\56\1\17\2\56\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\60\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\7"+
    "\2\10\1\37\1\12\1\7\1\13\1\7\1\14\1\40"+
    "\1\41\1\61\1\42\4\61\1\62\15\61\1\17\1\61"+
    "\1\63\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\64\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\7\2\10\1\37\1\12\1\7\1\13\1\7"+
    "\1\14\1\40\1\41\2\42\1\43\1\44\1\45\1\42"+
    "\1\46\1\42\1\47\1\50\2\42\1\51\1\52\1\53"+
    "\5\42\1\17\1\42\1\54\1\20\1\21\1\65\1\23"+
    "\1\24\1\25\1\26\1\55\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\4\66\1\67\44\66\1\70"+
    "\10\66\63\0\2\10\62\0\1\11\62\0\1\71\1\72"+
    "\54\0\1\73\2\0\3\73\1\74\1\75\52\73\1\76"+
    "\2\0\4\76\1\77\1\100\51\76\11\0\1\15\1\101"+
    "\24\15\1\0\2\15\7\0\1\15\21\0\1\102\1\103"+
    "\24\102\1\0\2\102\7\0\1\102\23\0\1\104\1\0"+
    "\22\104\1\0\2\104\7\0\1\104\21\0\1\105\1\0"+
    "\24\105\1\0\2\105\7\0\1\105\21\0\1\106\1\0"+
    "\24\106\1\0\2\106\7\0\1\106\21\0\1\107\2\0"+
    "\23\107\1\0\2\107\7\0\1\107\21\0\1\110\1\0"+
    "\24\110\1\0\2\110\7\0\1\110\16\0\1\111\1\0"+
    "\1\112\54\0\1\37\67\0\1\113\1\114\24\113\1\0"+
    "\2\113\7\0\1\113\21\0\1\102\1\115\24\102\1\0"+
    "\2\102\7\0\1\102\21\0\1\113\1\114\3\113\1\116"+
    "\1\117\17\113\1\0\2\113\7\0\1\113\21\0\1\113"+
    "\1\114\11\113\1\120\12\113\1\0\2\113\7\0\1\113"+
    "\21\0\1\113\1\114\5\113\1\121\3\113\1\122\12\113"+
    "\1\0\2\113\7\0\1\113\21\0\1\113\1\114\2\113"+
    "\1\123\4\113\1\124\14\113\1\0\2\113\7\0\1\113"+
    "\21\0\1\113\1\114\4\113\1\125\17\113\1\0\2\113"+
    "\7\0\1\113\21\0\1\113\1\114\2\113\1\126\7\113"+
    "\1\127\1\130\10\113\1\0\2\113\7\0\1\113\21\0"+
    "\1\113\1\114\2\113\1\131\21\113\1\0\2\113\7\0"+
    "\1\113\21\0\1\113\1\114\11\113\1\132\12\113\1\0"+
    "\2\113\7\0\1\113\21\0\1\113\1\114\7\113\1\133"+
    "\7\113\1\134\4\113\1\0\2\113\7\0\1\113\21\0"+
    "\1\54\1\114\2\54\22\113\1\0\1\113\1\54\7\0"+
    "\1\113\21\0\1\113\1\114\3\113\1\135\20\113\1\0"+
    "\2\113\7\0\1\113\21\0\1\56\1\136\24\56\1\0"+
    "\2\56\7\0\1\56\21\0\1\56\1\136\2\56\1\137"+
    "\21\56\1\0\2\56\7\0\1\56\21\0\1\56\1\136"+
    "\3\56\1\140\20\56\1\0\2\56\7\0\1\56\21\0"+
    "\1\113\1\114\24\61\1\0\2\61\7\0\1\61\21\0"+
    "\1\113\1\114\2\61\1\141\21\61\1\0\2\61\7\0"+
    "\1\61\21\0\1\54\1\114\2\63\22\61\1\0\1\61"+
    "\1\63\7\0\1\61\21\0\1\113\1\114\3\61\1\142"+
    "\20\61\1\0\2\61\7\0\1\61\10\0\67\66\1\143"+
    "\72\66\1\144\43\66\1\71\2\0\57\71\5\72\1\145"+
    "\54\72\1\73\2\0\3\73\1\146\1\75\52\73\6\0"+
    "\1\147\53\0\2\73\1\0\57\73\1\76\2\0\4\76"+
    "\1\77\1\146\53\76\1\0\57\76\10\0\1\150\63\0"+
    "\1\151\60\0\1\102\1\0\24\102\1\0\2\102\2\0"+
    "\1\152\4\0\1\102\21\0\1\151\1\0\24\151\1\0"+
    "\2\151\7\0\1\151\23\0\24\104\1\0\2\104\7\0"+
    "\1\104\21\0\1\107\2\0\23\107\1\0\2\107\2\0"+
    "\1\153\4\0\1\107\10\0\1\154\2\0\3\154\1\155"+
    "\1\156\52\154\1\157\2\0\4\157\1\160\1\161\51\157"+
    "\12\0\1\115\60\0\1\162\1\0\24\162\1\0\2\162"+
    "\7\0\1\162\21\0\1\113\1\114\4\113\1\163\17\113"+
    "\1\0\2\113\7\0\1\113\21\0\1\113\1\114\4\113"+
    "\1\116\17\113\1\0\2\113\7\0\1\113\21\0\1\113"+
    "\1\114\17\113\1\164\4\113\1\0\2\113\7\0\1\113"+
    "\21\0\1\113\1\114\3\113\1\120\20\113\1\0\2\113"+
    "\7\0\1\113\21\0\1\113\1\114\12\113\1\165\11\113"+
    "\1\0\2\113\7\0\1\113\21\0\1\113\1\114\10\113"+
    "\1\166\13\113\1\0\2\113\7\0\1\113\21\0\1\113"+
    "\1\114\7\113\1\167\14\113\1\0\2\113\7\0\1\113"+
    "\21\0\1\113\1\114\6\113\1\170\15\113\1\0\2\113"+
    "\7\0\1\113\21\0\1\113\1\114\3\113\1\171\20\113"+
    "\1\0\2\113\7\0\1\113\21\0\1\113\1\114\6\113"+
    "\1\172\15\113\1\0\2\113\7\0\1\113\21\0\1\113"+
    "\1\114\20\113\1\173\3\113\1\0\2\113\7\0\1\113"+
    "\21\0\1\113\1\114\15\113\1\116\6\113\1\0\2\113"+
    "\7\0\1\113\21\0\1\113\1\114\11\113\1\174\12\113"+
    "\1\0\2\113\7\0\1\113\21\0\1\113\1\114\4\113"+
    "\1\170\17\113\1\0\2\113\7\0\1\113\22\0\1\162"+
    "\60\0\1\56\1\136\12\56\1\175\11\56\1\0\2\56"+
    "\7\0\1\56\21\0\1\113\1\114\12\61\1\176\11\61"+
    "\1\0\2\61\7\0\1\61\10\0\5\143\1\177\54\143"+
    "\4\72\1\200\1\145\54\72\1\147\2\0\3\147\1\201"+
    "\1\202\52\147\1\150\2\0\4\150\1\203\1\204\51\150"+
    "\11\0\1\205\2\0\23\205\1\0\2\205\7\0\1\205"+
    "\10\0\1\154\2\0\3\154\1\206\1\156\52\154\6\0"+
    "\1\207\53\0\2\154\1\0\57\154\1\157\2\0\4\157"+
    "\1\160\1\206\53\157\1\0\57\157\10\0\1\210\62\0"+
    "\1\113\1\114\5\113\1\116\16\113\1\0\2\113\7\0"+
    "\1\113\21\0\1\113\1\114\22\113\1\211\1\113\1\0"+
    "\2\113\7\0\1\113\21\0\1\113\1\114\12\113\1\212"+
    "\11\113\1\0\2\113\7\0\1\113\21\0\1\113\1\114"+
    "\10\113\1\127\13\113\1\0\2\113\7\0\1\113\21\0"+
    "\1\113\1\114\11\113\1\213\12\113\1\0\2\113\7\0"+
    "\1\113\21\0\1\113\1\114\7\113\1\116\14\113\1\0"+
    "\2\113\7\0\1\113\21\0\1\113\1\114\11\113\1\116"+
    "\12\113\1\0\2\113\7\0\1\113\21\0\1\113\1\114"+
    "\11\113\1\214\12\113\1\0\2\113\7\0\1\113\21\0"+
    "\1\113\1\114\12\113\1\215\11\113\1\0\2\113\7\0"+
    "\1\113\21\0\1\113\1\114\23\113\1\116\1\0\2\113"+
    "\7\0\1\113\21\0\1\56\1\136\12\56\1\216\11\56"+
    "\1\0\2\56\7\0\1\56\21\0\1\113\1\114\12\61"+
    "\1\217\11\61\1\0\2\61\7\0\1\61\10\0\4\143"+
    "\1\220\1\177\54\143\6\0\1\221\53\0\2\147\1\0"+
    "\57\147\2\150\1\0\57\150\10\0\1\222\62\0\1\205"+
    "\2\0\23\205\1\0\2\205\4\0\1\34\2\0\1\205"+
    "\10\0\1\207\2\0\3\207\1\223\1\224\52\207\1\210"+
    "\2\0\4\210\1\225\1\226\51\210\11\0\1\113\1\114"+
    "\22\113\1\227\1\113\1\0\2\113\7\0\1\113\21\0"+
    "\1\113\1\114\5\113\1\230\16\113\1\0\2\113\7\0"+
    "\1\113\21\0\1\113\1\114\14\113\1\120\7\113\1\0"+
    "\2\113\7\0\1\113\21\0\1\113\1\114\10\113\1\231"+
    "\13\113\1\0\2\113\7\0\1\113\16\0\1\146\63\0"+
    "\1\146\57\0\1\232\53\0\2\207\1\0\57\207\2\210"+
    "\1\0\57\210\10\0\1\233\62\0\1\113\1\114\11\113"+
    "\1\163\12\113\1\0\2\113\7\0\1\113\21\0\1\113"+
    "\1\114\16\113\1\234\5\113\1\0\2\113\7\0\1\113"+
    "\21\0\1\113\1\114\2\113\1\235\21\113\1\0\2\113"+
    "\7\0\1\113\16\0\1\206\63\0\1\206\62\0\1\113"+
    "\1\114\17\113\1\127\4\113\1\0\2\113\7\0\1\113"+
    "\21\0\1\113\1\114\21\113\1\116\2\113\1\0\2\113"+
    "\7\0\1\113\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6300];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\1\1\11\12\1\1\11\1\1\1\11\2\1"+
    "\10\11\26\1\1\11\5\1\1\0\1\1\3\0\1\1"+
    "\3\0\5\1\5\0\1\1\16\0\1\1\1\0\7\1"+
    "\1\11\2\0\1\1\1\11\2\0\1\1\3\0\2\1"+
    "\12\0\3\1\1\11\5\0\1\11\3\0\1\1\3\0"+
    "\3\1\15\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  _ConkittyLexer() {
    this((java.io.Reader)null);
  }

  public int yycolumn = 0;
  public int yyline = 0;

  public final void setStart(int start) {
    zzCurrentPos = zzStartRead = start;
  }

  protected abstract void readJavaScript() throws java.io.IOException;
  protected abstract void readMultilineJavaScript() throws java.io.IOException;


  _ConkittyLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  _ConkittyLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 130) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch ((zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL] : zzBufferL.charAt(zzCurrentPosL))) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = (zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL] : zzBufferL.charAt(zzMarkedPosL)) == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = (zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL] : zzBufferL.charAt(zzMarkedPosL)) == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 27: 
          { yypushback(1); yybegin(NO_JS); return CSS_IF;
          }
        case 30: break;
        case 25: 
          { return COMMAND_NAME;
          }
        case 31: break;
        case 28: 
          { return INCLUDE;
          }
        case 32: break;
        case 19: 
          { return VARIABLE;
          }
        case 33: break;
        case 15: 
          { return COMMA;
          }
        case 34: break;
        case 4: 
          { yybegin(IN_TEMPLATE); return com.intellij.psi.TokenType.WHITE_SPACE;
          }
        case 35: break;
        case 14: 
          { return NODE_APPENDER;
          }
        case 36: break;
        case 21: 
          { return COMMENT;
          }
        case 37: break;
        case 1: 
          { readMultilineJavaScript(); return JAVASCRIPT;
          }
        case 38: break;
        case 2: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 39: break;
        case 6: 
          { readJavaScript(); return JAVASCRIPT;
          }
        case 40: break;
        case 24: 
          { return ATTR;
          }
        case 41: break;
        case 5: 
          { yybegin(IN_TEMPLATE); return TEMPLATE_NAME;
          }
        case 42: break;
        case 10: 
          { return LCBRACKET;
          }
        case 43: break;
        case 26: 
          { yybegin(MULTILINE_JS); return COMMAND_NAME;
          }
        case 44: break;
        case 3: 
          { yybegin(YYINITIAL); return CRLF;
          }
        case 45: break;
        case 9: 
          { return RSBRACKET;
          }
        case 46: break;
        case 8: 
          { return LSBRACKET;
          }
        case 47: break;
        case 12: 
          { return RET_MAKER;
          }
        case 48: break;
        case 20: 
          { yybegin(IN_TEMPLATE); return LBRACKET;
          }
        case 49: break;
        case 23: 
          { return CSS_ID;
          }
        case 50: break;
        case 22: 
          { return STRING;
          }
        case 51: break;
        case 29: 
          { yybegin(AFTER_CALL); return COMMAND_NAME;
          }
        case 52: break;
        case 13: 
          { return CSS_CLASS;
          }
        case 53: break;
        case 17: 
          { return CSS_TAG;
          }
        case 54: break;
        case 11: 
          { return RCBRACKET;
          }
        case 55: break;
        case 7: 
          { return RBRACKET;
          }
        case 56: break;
        case 18: 
          { yybegin(IN_CALL); return TEMPLATE_NAME;
          }
        case 57: break;
        case 16: 
          { return com.intellij.psi.TokenType.WHITE_SPACE;
          }
        case 58: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
