/* The following code was generated by JFlex 1.4.3 on 10/21/13 7:54 PM */

package com.hoho.conkitty;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import static com.hoho.conkitty.psi.ConkittyTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 10/21/13 7:54 PM from the specification file
 * <tt>/Users/hoho/Work/conkittyPlugin/src/com/hoho/conkitty/Conkitty.flex</tt>
 */
abstract class _ConkittyLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int IN_TEMPLATE = 6;
  public static final int YYINITIAL = 0;
  public static final int IN_JAVASCRIPT2 = 12;
  public static final int IN_CALL = 14;
  public static final int IN_VAR_DECL = 8;
  public static final int IN_JAVASCRIPT = 10;
  public static final int IN_COMMENT = 2;
  public static final int IN_LONG_COMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6, 6
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\0\1\10"+
    "\4\0\1\6\1\34\1\35\1\31\2\0\1\33\1\0\1\30\12\5"+
    "\6\0\1\32\1\11\1\4\1\14\1\27\1\21\2\4\1\16\1\22"+
    "\2\4\1\15\1\4\1\23\1\17\1\25\1\4\1\13\1\20\1\12"+
    "\2\4\1\24\1\4\1\26\1\4\1\0\1\7\2\0\1\4\1\0"+
    "\32\4\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\7\0\1\1\1\2\1\3\1\4\3\1\1\5\1\6"+
    "\11\1\12\7\1\1\1\10\1\11\10\12\10\13\2\14"+
    "\2\0\1\15\3\0\1\16\15\0\15\7\5\0\1\12"+
    "\6\0\1\13\1\0\1\14\7\0\1\17\5\0\5\7"+
    "\1\17\5\7\4\0\1\14\1\0\1\16\1\20\1\21"+
    "\3\0\1\20\1\21\3\7\1\0\1\12\1\0\1\13"+
    "\1\21\2\0\2\7\2\0\2\7";

  private static int [] zzUnpackAction() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\36\0\74\0\132\0\170\0\226\0\264\0\322"+
    "\0\360\0\u010e\0\u012c\0\u014a\0\u0168\0\u0186\0\322\0\322"+
    "\0\u01a4\0\u01c2\0\u01e0\0\u01fe\0\u021c\0\u023a\0\u0258\0\u0276"+
    "\0\u0294\0\u02b2\0\u02d0\0\u02ee\0\u030c\0\u032a\0\u0348\0\u0366"+
    "\0\u0384\0\u03a2\0\u03c0\0\u03de\0\u03fc\0\u041a\0\322\0\u0438"+
    "\0\u0456\0\u0474\0\u0492\0\u04b0\0\u04ce\0\u04ec\0\322\0\u050a"+
    "\0\u0528\0\u0546\0\u0564\0\u0582\0\u05a0\0\u05be\0\u05dc\0\u05fa"+
    "\0\u0186\0\u014a\0\322\0\u0618\0\u0168\0\u0636\0\u0654\0\u0672"+
    "\0\u0690\0\u06ae\0\u06cc\0\u06ea\0\u0708\0\u0726\0\u0744\0\u0762"+
    "\0\u0780\0\u079e\0\u07bc\0\u07da\0\u07f8\0\u0816\0\u0834\0\u0852"+
    "\0\u0870\0\u088e\0\u08ac\0\u08ca\0\u08e8\0\u0906\0\u0924\0\u0942"+
    "\0\u03de\0\u04ce\0\u0492\0\u0960\0\u04b0\0\u097e\0\u099c\0\u09ba"+
    "\0\u05a0\0\u0564\0\u09d8\0\u0582\0\u09f6\0\u0a14\0\u0a32\0\u0a50"+
    "\0\u0a6e\0\u0a8c\0\u0aaa\0\u0ac8\0\u0ae6\0\u0b04\0\u0b22\0\322"+
    "\0\u0b40\0\u0b5e\0\u0b7c\0\u0b9a\0\u0bb8\0\u0bd6\0\u0bf4\0\u0c12"+
    "\0\u0c30\0\u0c4e\0\u02b2\0\u0c6c\0\u0c8a\0\u0ca8\0\u0cc6\0\u0ce4"+
    "\0\u0d02\0\u0d20\0\u0d3e\0\u0d5c\0\u0d7a\0\u0d98\0\u0db6\0\322"+
    "\0\322\0\u0dd4\0\u0df2\0\u0e10\0\u02b2\0\u02b2\0\u0e2e\0\u0e4c"+
    "\0\u0e6a\0\u0e88\0\u0ea6\0\u0ec4\0\u0ee2\0\u05dc\0\u0f00\0\u0f1e"+
    "\0\u0f3c\0\u0f5a\0\u0f78\0\u0f96\0\u0fb4\0\u0fd2";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\10\2\11\1\12\1\13\1\10\1\14\1\10\1\15"+
    "\17\13\1\16\3\10\1\17\1\20\1\10\2\11\1\12"+
    "\2\10\1\14\1\10\1\15\1\21\1\22\1\10\1\23"+
    "\2\10\1\24\1\25\1\26\1\27\1\10\1\30\1\31"+
    "\2\10\1\16\3\10\1\17\1\20\1\10\2\11\1\12"+
    "\1\32\1\10\1\14\1\10\1\15\1\33\1\34\1\32"+
    "\1\35\2\32\1\36\1\37\1\40\1\41\1\32\1\42"+
    "\1\43\2\32\1\16\1\10\1\44\1\10\1\17\1\20"+
    "\1\10\2\45\1\12\1\46\1\10\1\14\1\10\1\15"+
    "\17\46\1\16\3\10\1\17\1\20\1\47\2\50\1\51"+
    "\1\52\1\47\1\53\1\47\1\54\17\52\1\55\1\47"+
    "\1\56\3\47\1\57\2\60\1\61\1\62\1\57\1\63"+
    "\1\57\1\64\17\62\1\65\1\57\1\66\3\57\1\10"+
    "\2\11\1\12\1\67\1\10\1\14\1\10\1\15\3\67"+
    "\1\70\13\67\1\16\3\10\1\17\1\20\37\0\2\11"+
    "\36\0\1\12\24\0\1\71\11\0\2\13\3\0\17\13"+
    "\6\0\6\72\1\73\1\74\26\72\7\75\1\76\1\73"+
    "\25\75\30\0\1\77\1\100\16\0\1\101\44\0\1\102"+
    "\25\0\1\103\4\0\1\104\31\0\1\105\44\0\1\106"+
    "\25\0\1\107\3\0\1\110\43\0\1\111\30\0\1\112"+
    "\3\0\1\113\24\0\1\114\30\0\2\32\3\0\17\32"+
    "\12\0\2\32\3\0\1\32\1\115\15\32\12\0\2\32"+
    "\3\0\10\32\1\116\6\32\12\0\2\32\3\0\1\117"+
    "\4\32\1\120\11\32\12\0\2\32\3\0\1\32\1\121"+
    "\15\32\12\0\2\32\3\0\10\32\1\122\6\32\12\0"+
    "\2\32\3\0\1\123\3\32\1\124\12\32\12\0\2\32"+
    "\3\0\12\32\1\125\4\32\12\0\2\32\3\0\5\32"+
    "\1\126\3\32\1\127\5\32\12\0\2\32\3\0\1\130"+
    "\16\32\12\0\1\131\4\0\17\131\3\0\1\131\3\0"+
    "\2\45\37\0\2\46\3\0\17\46\7\0\2\50\36\0"+
    "\1\51\24\0\1\132\11\0\2\52\3\0\17\52\6\0"+
    "\6\133\1\47\1\134\26\133\7\135\1\136\1\47\25\135"+
    "\30\0\1\137\1\140\10\0\1\56\4\0\17\56\3\0"+
    "\1\56\3\0\2\60\36\0\1\61\24\0\1\141\11\0"+
    "\2\62\3\0\17\62\6\0\6\142\1\57\1\143\26\142"+
    "\7\144\1\145\1\57\25\144\30\0\1\146\1\147\10\0"+
    "\1\66\4\0\17\66\3\0\1\66\6\0\2\67\3\0"+
    "\17\67\12\0\2\67\3\0\1\150\16\67\6\0\2\72"+
    "\1\0\33\72\2\75\1\0\33\75\1\77\2\0\33\77"+
    "\31\151\1\152\4\151\12\0\1\153\43\0\1\154\32\0"+
    "\1\155\37\0\1\156\34\0\1\157\31\0\1\160\37\0"+
    "\1\161\41\0\1\162\35\0\1\163\36\0\1\164\26\0"+
    "\1\161\51\0\1\165\13\0\2\32\3\0\1\32\1\166"+
    "\15\32\12\0\2\32\3\0\7\32\1\167\7\32\12\0"+
    "\2\32\3\0\4\32\1\170\12\32\12\0\2\32\3\0"+
    "\6\32\1\171\10\32\12\0\2\32\3\0\5\32\1\172"+
    "\11\32\12\0\2\32\3\0\1\32\1\173\15\32\12\0"+
    "\2\32\3\0\3\32\1\174\13\32\12\0\2\32\3\0"+
    "\7\32\1\175\7\32\12\0\2\32\3\0\7\32\1\176"+
    "\7\32\12\0\2\32\3\0\10\32\1\177\6\32\12\0"+
    "\2\32\3\0\1\32\1\174\15\32\12\0\2\32\3\0"+
    "\15\32\1\200\1\32\6\0\2\133\1\0\33\133\2\135"+
    "\1\0\33\135\1\137\2\0\33\137\31\201\1\202\4\201"+
    "\2\142\1\0\33\142\2\144\1\0\33\144\1\146\2\0"+
    "\33\146\31\203\1\204\4\203\4\0\2\67\3\0\4\67"+
    "\1\205\12\67\6\0\31\151\1\206\4\151\30\0\1\207"+
    "\1\152\17\0\1\210\34\0\1\210\40\0\1\211\37\0"+
    "\1\110\37\0\1\212\32\0\1\160\40\0\1\210\35\0"+
    "\1\213\37\0\1\210\27\0\1\214\24\0\2\32\3\0"+
    "\2\32\1\215\14\32\12\0\2\32\3\0\1\32\1\215"+
    "\15\32\12\0\2\32\3\0\4\32\1\216\12\32\12\0"+
    "\2\32\3\0\6\32\1\124\10\32\12\0\2\32\3\0"+
    "\10\32\1\217\6\32\12\0\2\32\3\0\5\32\1\173"+
    "\11\32\12\0\2\32\3\0\10\32\1\215\6\32\12\0"+
    "\2\32\3\0\10\32\1\220\6\32\12\0\2\32\3\0"+
    "\12\32\1\215\4\32\12\0\2\32\3\0\4\32\1\221"+
    "\12\32\6\0\31\201\1\222\4\201\30\0\1\223\1\202"+
    "\4\0\31\203\1\224\4\203\30\0\1\225\1\204\10\0"+
    "\2\67\3\0\4\67\1\226\12\67\6\0\30\151\1\207"+
    "\1\206\4\151\3\0\1\207\45\0\1\227\35\0\1\154"+
    "\41\0\1\230\22\0\2\32\3\0\2\32\1\231\14\32"+
    "\12\0\2\32\3\0\2\32\1\167\14\32\12\0\2\32"+
    "\3\0\6\32\1\232\10\32\6\0\30\201\1\223\1\222"+
    "\4\201\3\0\1\223\32\0\30\203\1\225\1\224\4\203"+
    "\3\0\1\225\56\0\1\233\22\0\1\234\30\0\2\32"+
    "\3\0\13\32\1\235\3\32\12\0\2\32\3\0\1\236"+
    "\16\32\30\0\1\110\42\0\1\210\12\0\2\32\3\0"+
    "\11\32\1\124\5\32\12\0\2\32\3\0\16\32\1\215"+
    "\6\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4080];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\7\0\1\11\6\1\2\11\26\1\1\11\7\1\1\11"+
    "\11\1\2\0\1\11\3\0\1\1\15\0\15\1\5\0"+
    "\1\1\6\0\1\1\1\0\1\1\7\0\1\11\5\0"+
    "\13\1\4\0\1\1\1\0\1\1\2\11\3\0\5\1"+
    "\1\0\1\1\1\0\2\1\2\0\2\1\2\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  _ConkittyLexer() {
    this((java.io.Reader)null);
  }

  public final void setStart(int start) {
    zzCurrentPos = zzStartRead = start;
  }

  private int afterJavaScript = YYINITIAL;

  protected abstract void readJavaScript(int state) throws java.io.IOException;


  _ConkittyLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  _ConkittyLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 104) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 2: 
          { return CRLF;
          }
        case 18: break;
        case 3: 
          { return WHITE_SPACE;
          }
        case 19: break;
        case 17: 
          { yybegin(IN_CALL); return KEYWORD;
          }
        case 20: break;
        case 5: 
          { afterJavaScript = yystate(); yybegin(IN_JAVASCRIPT); return JAVASCRIPT_BEGIN;
          }
        case 21: break;
        case 12: 
          { yybegin(IN_TEMPLATE); return TEMPLATE_NAME;
          }
        case 22: break;
        case 16: 
          { return KEYWORD;
          }
        case 23: break;
        case 11: 
          { return JAVASCRIPT;
          }
        case 24: break;
        case 15: 
          { yybegin(IN_VAR_DECL); return KEYWORD;
          }
        case 25: break;
        case 4: 
          { yybegin(IN_VAR_DECL); return TEMPLATE_NAME;
          }
        case 26: break;
        case 14: 
          { return COMMENT;
          }
        case 27: break;
        case 8: 
          { yybegin(IN_TEMPLATE); return CRLF;
          }
        case 28: break;
        case 1: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 29: break;
        case 10: 
          { yybegin(IN_JAVASCRIPT2); readJavaScript(afterJavaScript); return JAVASCRIPT;
          }
        case 30: break;
        case 7: 
          { return CSS;
          }
        case 31: break;
        case 13: 
          { return STRING;
          }
        case 32: break;
        case 6: 
          { return JAVASCRIPT_END;
          }
        case 33: break;
        case 9: 
          { return VARIABLE;
          }
        case 34: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
