{
  parserClass="com.hoho.conkitty.parser.ConkittyParser"
  stubParserClass="com.hoho.conkitty.parser.GeneratedParserUtilBase"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Conkitty"
  psiImplClassSuffix="Impl"
  psiPackage="com.hoho.conkitty.psi"
  psiImplPackage="com.hoho.conkitty.psi.impl"

  elementTypeHolderClass="com.hoho.conkitty.psi.ConkittyTypes"
  elementTypeClass="com.hoho.conkitty.psi.ConkittyElementType"
  tokenTypeClass="com.hoho.conkitty.psi.ConkittyTokenType"
}

private elements ::= TEMPLATE_NAME COMMAND_NAME VARIABLE LBRACKET RBRACKET LSBRACKET RSBRACKET LCBRACKET RCBRACKET COMMA JAVASCRIPT STRING CSS_TAG CSS_CLASS CSS_ID CSS_BEM CSS_BEM_MOD CSS_ATTR CSS_ATTR_NAME CSS_IF ATTR INCLUDE ARGUMENT_DECL ARGUMENT_VAL NODE_APPENDER ASSIGN COMMENT CRLF

root ::= elements
